### ISSUE TITLE
Concrete Strength Prediction

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/DataDen#2]
- **Objective** : To create a model which can predict the strength of the cement (in MPa)
- **Dataset Link**:https://www.kaggle.com/datasets/maajdl/yeh-concret-data
- Do Exploratory Data Analysis, create models using different algorithms and compare them using accuracy scores.

**Comment by tarushsingh09** [comment]
Please assign this to me.

**Comment by AshishKingdom** [comment]
hey @tarushsingh09 , you can start working on it! :)

**Comment by tarushsingh09** [comment]
Sure!
Thank You
Tarush Singh

**Comment by AshishKingdom** [comment]
merged in #20
