### ISSUE TITLE
Student Performance

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/DataDen#3]
- **Objective** : To create a model which can predict the performance index of the student (0-100)
- **Dataset Link**: https://www.kaggle.com/datasets/nikhil7280/student-performance-multiple-linear-regression
- Do Exploratory Data Analysis, create models using different algorithms and compare them using accuracy scores.

**Comment by Karurot** [comment]
Please assign this to me.

**Comment by AshishKingdom** [comment]
hii @Karurot , I have assigned this issue to you. You can start working on it! :)

**Comment by Karurot** [comment]
pull request #19 made for this issue

**Comment by AshishKingdom** [comment]
merged
