### ISSUE TITLE
Real Estate House Prediction

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/DataDen#4]
- **Objective**: To create a model which can predict the price of the house using various factor (age, location, etc)
- **Dataset Link**:https://www.kaggle.com/datasets/quantbruce/real-estate-price-prediction
- Do Exploratory Data Analysis, create models using different algorithms, and compare them using accuracy scores.

**Comment by AdityaDKale** [comment]
Can I work on this issue?
