### ISSUE TITLE
GPU Kernel Performance

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/DataDen#6]
- **Objective** : Implement a linear regression model on the dataset to predict the GPU run time. Use the average of four runs as the target variable.
- **Dataset Link**: https://www.kaggle.com/datasets/rupals/gpu-runtime?select=sgemm_product.csv
- Do Exploratory Data Analysis, create models using different algorithms and compare them using accuracy scores.

**Comment by Zhreyu** [comment]
Hey, I would like to work on this, can you please assign me this issue?

**Comment by AshishKingdom** [comment]
Hi @Zhreyu!
Sure, you can start working on it!

**Comment by Zhreyu** [comment]
![image](https://github.com/DSC-JSS-NOIDA/DataDen/assets/96978606/6e7947e7-d19b-4aeb-aabc-aab8ba4fe69c)
Can you please lmk if this folder structure is fine?, I am yet to create a readme.md file tho , all these files are in a folder called GPU kernal performance analysis

**Comment by AshishKingdom** [comment]
Yeah, everything looks good!

**Comment by AshishKingdom** [comment]
done in PR #16
