### ISSUE TITLE
Diamond Price Predication/Calculation

### ISSUE THREAD

**Issue by AshishKingdom** [DSC-JSS-NOIDA/DataDen#9]
- **Objective** : To create a model which can predict the price of the diamond based on various parameters (color,carat,cut,etc)
- **Dataset Link**:https://www.kaggle.com/datasets/ronil8/diamond-price-prediction-dataset
- Do Exploratory Data Analysis, create models using different algorithms and compare them using accuracy scores.

**Comment by baghel24** [comment]
please assign to me

**Comment by AshishKingdom** [comment]
hey @baghel24 , I have already assigned you issue #14 .

**Comment by Sarthak350** [comment]
please assign this to me

**Comment by AshishKingdom** [comment]
@Sarthak350 assigned

**Comment by AshishKingdom** [comment]
completed in #21
